# Generated by Django 2.2 on 2019-04-06 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='status',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='bin',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
