# Generated by Django 2.2 on 2019-04-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190406_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
