# Generated by Django 2.2 on 2019-04-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190407_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='slug',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
